# NOTE: Scheduled workflows run on the latest commit on the default or base branch.
name: Cron Example
on:
  # run every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
  # enables ability to use POST command to trigger workflow
  repository_dispatch:
# 
jobs:
  cron-linux-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Directory Bash
        run: pwd
        shell: bash
        # /home/runner/work/github-actions-test/github-actions-test
      - name: LS Directory Bash
        run: ls -al
        shell: bash
        # NOTE: This working directory is empty
      - name: Some GITHUB Environment Variables
        shell: bash
        run: |
          printenv | grep 'GITHUB_EVENT_NAME\|GITHUB_REF'
          echo "${{github.event.action}}"
