# note workflows and jobs run in parallel
name: Events Example
on: [push, pull_request, workflow_dispatch]
jobs:
  run-linux-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Directory Bash
        run: pwd
        shell: bash
        # /home/runner/work/github-actions-test/github-actions-test
      - name: LS Directory Bash
        run: ls -al
        shell: bash
        # NOTE: This working directory is empty
      # now lets checkout our repo instead
      # see https://github.com/actions/checkout#usage for options
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout Directory Bash
        run: pwd
        shell: bash
        # /home/runner/work/github-actions-test/github-actions-test
      - name: LS Checkout Directory Bash
        run: ls -al
        shell: bash
        # total 20
        # drwxr-xr-x 4 runner docker 4096 Dec  1 16:29 .
        # drwxr-xr-x 3 runner docker 4096 Dec  1 16:29 ..
        # drwxr-xr-x 8 runner docker 4096 Dec  1 16:29 .git
        # drwxr-xr-x 3 runner docker 4096 Dec  1 16:29 .github
        # -rw-r--r-- 1 runner docker   21 Dec  1 16:29 README.md
      - name: Environment Variables and Misc
        shell: bash
        run: |
          printenv | grep 'GITHUB'
          echo "${{github.token}}"
          git remote -vv
          git status
  run-windows-commands:
    runs-on: windows-latest
    # this causes this to run in series to 
    needs: [run-linux-commands]
    steps:
      - name: Directory Bash
        run: pwd
        shell: bash
        # /d/a/github-actions-test/github-actions-test
      - name: LS Directory Bash
        run: ls -al
        shell: bash
        # NOTE: This working directory is empty
      # now lets checkout our repo instead
      # see https://github.com/actions/checkout#usage for options
      - name: Checkout
        uses: actions/checkout@v1
        # same as above
      - name: Checkout Directory Bash
        run: pwd
        shell: bash
        # /d/a/github-actions-test/github-actions-test
      - name: LS Checkout Directory Bash
        run: ls -al
        shell: bash
        # total 5
        # drwxr-xr-x 1 runneradmin 197121  0 Dec  1 16:30 .
        # drwxr-xr-x 1 runneradmin 197121  0 Dec  1 16:30 ..
        # drwxr-xr-x 1 runneradmin 197121  0 Dec  1 16:30 .git
        # drwxr-xr-x 1 runneradmin 197121  0 Dec  1 16:30 .github
        # -rw-r--r-- 1 runneradmin 197121 21 Dec  1 16:30 README.md
      - name: Environment Variables and Misc
        shell: bash
        run: |
          printenv | grep 'GITHUB'
          echo "${{github.token}}"
          git remote -vv
          git status
        # similar to above but with Windows pathing - why?
