name: Matrix
on: [push, workflow_dispatch]
# example setting up node js using
# https://github.com/actions/setup-node
jobs:
  node-version:
    # using matrix strategy will run job for each matrix combination
    strategy:
      matrix:
        # this actually runs 9 jobs, one for each node_version/os combination
        node_version: [6,8,10]
        os: [macos-latest, ubuntu-latest, windows-latest]
        # you can exclude cobinations e.g.
        exclude:
          - os: macos-latest
            node_version: 8
          - os: windows-latest
            node_version: 6
          - os: windows-latest
            node_version: 8
        # you can add variables to specific matrix entries using include
        include:
          - os: windows-latest
            node_version: 8
            desired_version: "true"

      # failfast will cause any remaining jobs to fail if one job fails
      # failfast: true
      # max-parrallel - by default GitHub optimizes the parrallelism but you can force
      # max-parallel: 2
    # use matrix defined OS
    runs-on: ${{matrix.os}}
    steps:
    - name: Log node node-version
      run: node -v
    # step to install node version based on matrix value
    - uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node_version}}
    - name: Log node node-version
      run: |
        node -v
        echo "${{matrix.desired_version}}"
