# note workflows and jobs run in parallel
name: Shell Commands
on: [push, workflow_dispatch]
jobs:
  run-linux-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
        # v16.18.1
        # 8.19.2          
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
        # x86_64
      - name: Directory Bash
        run: pwd
        shell: bash
        # /home/runner/work/github-actions-test/github-actions-test
      - name: LS Directory Bash
        run: ls -al
        shell: bash
        # NOTE: This working directory is empty
      # now lets checkout our repo instead
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout Directory Bash
        run: pwd
        shell: bash
      - name: LS Checkout Directory Bash
        run: ls -al
        shell: bash
  run-windows-commands:
    runs-on: windows-latest
    # this causes this to run in series to 
    needs: [run-linux-commands]
    steps:
      - name: Directory Powershell
        run: Get-Location
        # Path
        # ----
        # D:\a\github-actions-test\github-actions-test
      - name: Directory Windows Shell
        run: cd
        shell: cmd
        # D:\a\github-actions-test\github-actions-test
      - name: Directory Bash
        run: pwd
        shell: bash
        # /d/a/github-actions-test/github-actions-test
      - name: LS Directory Bash
        run: ls -al
        shell: bash
        # NOTE: This working directory is empty
      # now lets checkout our repo instead
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout Directory Bash
        run: pwd
        shell: bash
      - name: LS Checkout Directory Bash
        run: ls -al
        shell: bash
