# note workflows run in parallel
name: Shell Commands
on: [push, workflow_dispatch]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
      - name: Directory Bash
        run: pwd
        shell: bash
  run-windows-commands:
    runs-on: windows-latest
    # this causes this to run in series to 
    needs: [run-shell-command]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
      - name: Directory Windows Shell
        run: cd
        shell: cmd
      - name: Directory Bash
        run: pwd
        shell: bash
